# Licensed to the Apache Software Foundation (ASF) under one
# or more contributor license agreements...

name: Manual Build Docker Image For Release

on:
  workflow_dispatch:
    inputs:
      tag_name:
        type: string
        required: true
        description: 'DockerHub img tag name'

jobs:
  build:
    if: ${{ github.repository_owner == 'Oreoro' }}  # Fixed case sensitivity
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Docker meta
      id: meta
      uses: docker/metadata-action@v4
      with:
        images: oreoro/answer  # Changed from apache/answer
        tags: |
          type=ref,enable=true,priority=600,prefix=,suffix=,event=branch
          type=semver,pattern={{version}}

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Login to DockerHub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USER }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build and push
      uses: docker/build-push-action@v4
      with:
        context: .  # Explicit context to use local files
        platforms: linux/amd64,linux/arm64
        push: true
        file: ./Dockerfile
        tags: oreoro/answer:${{ inputs.tag_name }}
        labels: ${{ steps.meta.outputs.labels }}
